services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    hostname: traefik
    networks:
      - server
    ports:
      - 80:80
      - 443:443
    environment:
      HOST: $HOST
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik/acme
      - ./configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./configs/traefik/routing:/etc/traefik/routing:ro

volumes:
  traefik_data:

networks:
  server:
    driver: bridge